# Site settings
title: ryanandme
tagline: Ryan Reviews with memories, not promotion
description: "This is a place where a fan of kakofriends Ryan in Korea speaks honestly with memories of Ryan's products."
url: "https://ryanandme.me"
author:
  name: "junian"
  email: "wns6614@naver.com"
  url: "https://ryanandme.me"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: /:title
paginate: 8

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: ryanandme
